### ISSUE TITLE
TypeError: _User2.default.create is not a function

### ISSUE THREAD

**Issue by JOAOSC17** [JOAOSC17/api-ecommerce#1]
Toda que tento fazer uma requisição em users  aparece o seguinte erro `TypeError: _User2.default.create is not a function`
Os models estão sento ultilizado em controllers e no index.js da pasta database

**Comment by italosantana** [comment]
@JOAOSC17  tenta dá uma olhadinha nesse link aqui, pois[ teve um problema similar com o seu](https://stackoverflow.com/questions/33313569/sequelize-create-is-not-a-function-error/33314192) que vi que não tá atribuido todos schema ao export.module = [].... e tbm dá uma olhadinha [nesse projeto](https://github.com/manikandanraji/youtubeclone-backend) que foi feito com seq tbm com 6 models e dá pra tu ter noção de como modelar, pois acredito que seja esse o erro.

**Comment by JOAOSC17** [comment]
muito obrigado @italosantana me ajudou muito o material
