### ISSUE TITLE
order 

### ISSUE THREAD

**Issue by JOAOSC17** [JOAOSC17/api-ecommerce#6]
tô tentando fazer um endpoint de pedidos nesse projeto e não tô conseguindo avançar pq não consigo incluir os dados do produto junto do pedido solicitado dentro de um loop.
o arquivo da rota : https://github.com/JOAOSC17/api-ecommerce/blob/order/src/routes/OrderRoutes.js#L53
as ultimas alterações do projeto: https://github.com/JOAOSC17/api-ecommerce/pull/5

**Comment by tonhao-dev** [comment]
No arquivo src/routes/OrderRoutes.js, `products_id` é um array com o id dos produtos escolhidos e `quantity_buyed` é um array que guarda a quantidade de produtos comprados em cada posição correto? algo como:

products_id       => [1, 2, 3, 4]
quantity_buyed => [2, 1, 5, 1]

**Comment by JOAOSC17** [comment]
muito obrigado @luis-antonio-ac  pela ajuda mas o problema foi já foi resolvido
